host: sgnlpa.vbrani.aisingapore.net

ui:
  name: ui
  port: 8080
  image: registry.aisingapore.net/sg-nlp/sg-nlp-ui:latest
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"

docs:
  name: docs
  port: 80
  image: registry.aisingapore.net/sg-nlp/docs:latest
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"

models:
  lsr:
    name: lsr
    port: 8000
    path: /api/relation-extraction/lsr/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sg-nlp/lsr:latest
    resources:
      requests:
        memory: "3Gi"
        cpu: "500m"
    healthcheck: true
  recconSpanExtraction:
    name: span-extraction
    port: 8000
    path: /api/span-extraction/spanbert/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sg-nlp/reccon-span-extraction:latest
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
    healthcheck: true
  recconEmotionEntailment:
    name: emotion-entailment
    port: 8000
    path: /api/emotion-entailment/roberta-base/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sg-nlp/reccon-emotion-entailment:latest
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
    healthcheck: true
  grammaticalErrorCorrection:
    name: grammatical-error-correction
    port: 8000
    path: /api/grammatical-error-correction/csgec/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sg-nlp/crosentgec:latest
    resources:
      requests:
        memory: "2.5Gi"
        cpu: "500m"
  rumourDetectionTwitter:
    name: rumour-detection-twitter
    port: 8000
    path: /api/rumour-detection-twitter/rumour-detection-twitter/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sg-nlp/rumour-detection-twitter:latest
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
    healthcheck: true
