const examples: Record<string, string>[] = [
  {
    essay:
      "Did you know that more and more people these days are depending on computers for their safety, natural education, and their social life? In my opinion, the increasing use of computers is not benefiting society. Initially, ones safety while using a computer is at risk. To begin, when someone is talking to another on a computer, they @MONTH1 never know who is at the other end of it. For example, @CAPS1 a small girl was playing a game on the computer and a person began talking to her, it could be a predator. She will never know unless they meet us somewhere. At this point, it maybe too late. Moreover, studies show that @PERCENT1 of people's information is more widely exposed in the last @NUM1 years due to the new chat websites. Such as myspace and facebook. In these websites, people share their information. With this, their safety is at risk. Finally, people should stop using computers as much as they are now, in order to keep their safety safe. Furthermore, enjoying nature is a must, in our world full of immense landscapes, wide waters, dense forests, and lush valleys. @CAPS1 you depend on your computer to teach you about the world, you should cease this use. One must actually be outside, experiencing the feel, the smell, and even the taste of nature. A recent study shows that people who actually went to the grand canyon could write a @NUM1 page essay on what they had learned. The people who didn't go and simply read information off their computer, could not write this much. Finally, society needs to back away from their computers, and stop into. Thirdly, a person's social life could be ruined from the use of computers for many reasons. One reasons for this could be that a person spends all their time on their computer instead of spending time with their family and friends. Sure, you can chat with people online, but that's nothing like chatting in person. There is no need to talk to a friend or family member online, when you could do it in person. Finally, @CAPS1 someone takes an embarrasing picture of you and puts it on their computer, it is there forever. Thus, you can lose friends, whether you're the person in the picture or the addict who put the picture on. With this, you can easily ruin your family/social life by using your computer too often. How would you feel @CAPS1 it was your fault that someone's safety is at risk? Wouldn't you rather enjoy nature in person instead of which it on your computer and not get the fall effect? Couldn't you talk to your friends and family in person rather than ignore them to use your computer? There are numerous ways in which the increasing rate of computer use does not benefit society. I encourage you to agree with me that computers can put one safety at risk decrease their education of nature and ruin their social life.",
    display: "Did you know that more and more people these days ...",
  },
  {
    essay:
      "Dear local newspaper, @CAPS1 you know how long you go on the computer for? Well get up and go outside. That's one of my reasons why I think people spend to much time on it my other reason is your eyes it can go bad. Its a nice sunny day don't wasn't your time on the computer! Go outside! All, kids @CAPS1 is sit on the computer all day not getting exercise. Did you know @NUM1 out of @NUM2 kids that sit on the computers all day gain at least @NUM3? @PERSON1 told me that. I mean I believe him because its true kids don't get up. There missing a nice day out would you wanna miss a nice sunny day? My final reason is kids eyesight can go bad. I mean having them stare at a screen all day, that's bad. @PERSON1 told me if your on the computer for @NUM4 hours on the computer for @NUM4 hours straight your eyes can get worst. I remember a tiny when I was on the computer for @NUM4 1/@NUM4 hours my eyes were killing me everything I blink. I know the computer is fun playing games, talking to friends but you should take a break and @CAPS1 something please. In conclusion just go outside and have fun! @CAPS1 you want to wasn't a nice sunny day by staying in doors hurting your eyes? I know I @CAPS1!",
    display: "Dear local newspaper, @CAPS1 you know how long you go on the computer for? ...",
  },
  {
    essay:
      "Computers are used world wide everyday, and most of the time @CAPS2 is used for a good reason. Computers help out by making @CAPS2 possible to get all the info you want, like for a trip. @CAPS1 you wanted to go to a close but fancy restaurant you @MONTH1 use a computer so you know how far. Computers also help out, making @CAPS2 possible to talk to friends that you haven't seen for years. @CAPS2 is also great way to meet new people. Let's say you are really stressed at work or school and you forget your book, you can usually bring @CAPS2 up on the computer and do @CAPS2 there. First, computers help out with traveling, sight seeing and lots more. When you travel, don't you want to know everything? And the biggest detail you want to know is the cost and the computer can usually give you a close to exact price for everything. Now that help's out a bunch when your traveling the world. And also when your site seeing you usually want to find either the most amazing or romantic spot were you are. And @CAPS1 you type in 'the most romantic spot in somers' @CAPS2 should come up with a bunch of spots. So don't drive to miles just to get a map or brochure, use your computer and print one off. Second, @CAPS1 there was a friend you haven't seen in years and you want to talk, you can go on the computer. The computer helps in so many ways @CAPS2 could even tell you were this person lives and you could surprise visit him/her. When your on the computer, you can even meet new friends and have conversations with them. and even meet them someday. And @CAPS1 you and that new friend get along then maybe you and that person could be best friends. So @CAPS1 you haven't seen or talked to someone in a while that you knew use the computer to have a chat. Third, say your teacher or boss yelled at you today and no one has been nice to you all day and you forget your homework book or paperwork. Were do you go? the computer, @CAPS2 can bring most any paper work or work book you need to get the job done. @CAPS1 you forgot your homework book, you don't want to get a falling grade. on this homework. So you go to your computer from there. And @CAPS1 you forgot your paper work, and @CAPS1 you didn't finish this project for work tonight you would be fired, you could just go on the computer, find the work and finish @CAPS2. Also save your job. So that why computers help out so much in this lifetime. Last, that is why in this lifetime you need computers. They help us with our vacation trips. They help with conversation with old friends we haven't seen forever. Also they help with your school and job work. At least @PERCENT1 of our population use computers every day and with out them our society would collapse @DATE1. So think about the decision you are making and @CAPS1 @CAPS2 will benefit our society or make our society @DATE1 to its knees.",
    display: "Computers are used world wide everyday ...",
  },
  {
    essay:
      "Computers, computers, computers. Who doesn't own them right? They teach hand eye coordination, give people to learn about faraway places and people can you actually believe some people say otherwise? I think that's pure bull !@. Computer's today help us with everyday tools, such as cars, cellphones and your everday television! Computer's also make work easier, and you interact with people! I for one think computers benefit society today, and those people who think otherwise should look into it one move step. Cellphones, cars, telephones want! There all made by mankind, but with a bit of technology. Did you know that @PERCENT1 of cars have computers biult in em? By the press of the button, all doors unlocked, by a swith the windows go down, yes, by computer. Now, how do computer's make life easier you say? Well keep reading to find out! The toothpaste, the baseball bats the pencils you we are all made by, the yoou know what! Machines, but programed with computer chips. Oh i remember when my history teacher told me that it took @NUM1 hours to make a baseball bat by a human from scratch. Now it takes like @NUM2 minutes with the help of comuters. If this isn't enough to tell you that computers benefit us, then what will?! Experts say people who use computers a lot don't get outside often to interact with family, but that's false I say! Cellphones are a everyday tool, we use them to talk with each other of long distant calls pay? Well then chat online on your own personal labtop! I hope now you believe computers do really benefit us. With there everday items we use, how they make work easier, and how it does make us interact. We use them everday, and hopefully they'll be around for the longest.",
    display: "Computers, computers, computers. Who doesn't own them right? ...",
  },
];

export default examples;
