const examples: Record<string, string>[] = [
  {
    essay:
      "Did you know that more and more people these days are depending on computers for their safety, natural education, and their social life? In my opinion, the increasing use of computers is not benefiting society. Initially, ones safety while using a computer is at risk. To begin, when someone is talking to another on a computer, they @MONTH1 never know who is at the other end of it. For example, @CAPS1 a small girl was playing a game on the computer and a person began talking to her, it could be a predator. She will never know unless they meet us somewhere. At this point, it maybe too late. Moreover, studies show that @PERCENT1 of people's information is more widely exposed in the last @NUM1 years due to the new chat websites. Such as myspace and facebook. In these websites, people share their information. With this, their safety is at risk. Finally, people should stop using computers as much as they are now, in order to keep their safety safe. Furthermore, enjoying nature is a must, in our world full of immense landscapes, wide waters, dense forests, and lush valleys. @CAPS1 you depend on your computer to teach you about the world, you should cease this use. One must actually be outside, experiencing the feel, the smell, and even the taste of nature. A recent study shows that people who actually went to the grand canyon could write a @NUM1 page essay on what they had learned. The people who didn't go and simply read information off their computer, could not write this much. Finally, society needs to back away from their computers, and stop into. Thirdly, a person's social life could be ruined from the use of computers for many reasons. One reasons for this could be that a person spends all their time on their computer instead of spending time with their family and friends. Sure, you can chat with people online, but that's nothing like chatting in person. There is no need to talk to a friend or family member online, when you could do it in person. Finally, @CAPS1 someone takes an embarrasing picture of you and puts it on their computer, it is there forever. Thus, you can lose friends, whether you're the person in the picture or the addict who put the picture on. With this, you can easily ruin your family/social life by using your computer too often. How would you feel @CAPS1 it was your fault that someone's safety is at risk? Wouldn't you rather enjoy nature in person instead of which it on your computer and not get the fall effect? Couldn't you talk to your friends and family in person rather than ignore them to use your computer? There are numerous ways in which the increasing rate of computer use does not benefit society. I encourage you to agree with me that computers can put one safety at risk decrease their education of nature and ruin their social life.",
    display: "Did you know that more and more people these days ...",
  },
  {
    essay:
      "There are some effects computers have on people that I agree with and disagree with. There are many people in the world that use computers every day and some that use it sometimes. Also it always gives you information everytime you use it. I would think that computers give a positive effect on people. Computers can have their likes and dislikes. Not everytime when you need information the computer won't give it to you. There are some websites that give you the right stuff you want to know and others do not fill your mind with positive things. That is one thing I do not like about computers. Do not think that is too bad because computers have alot more fun adavantages. One of the most common and used thing around the world is instant @CAPS7. Instant @CAPS7 is when you are communicating with another human bean over the online web. Many people use this to get in touch with a close family members or a friend. There are some names for instant @CAPS7 @CAPS1 @CAPS2, @CAPS3, @CAPS4-mail, and many more! Yes, the computer can be very addicting but once in a while you need to get off and maybe get some fresh air. For some people I agree that they stay on the computer to much and became very lazy. This is one disadvantage that can cause you from exercizing and seeing friends and family. There is no problem if you go on for an hour a day maybe more, but to long is not good. There are so many things for the computer I can't name them all @CAPS5, @CAPS6, @ORGANIZATION1, @CAPS7, and even buying things off the computers, those are many of the things you can do on your computer. I love going on the computer time to time doing many things I have talked about. Also if you do have one than reading this @MONTH1 persuade you into getting one. My opinion is that they give you a very positive effect.",
    display: "There are some effects computers have on people ...",
  },
  {
    essay:
      "Computers, computers, computers. Who doesn't own them right? They teach hand eye coordination, give people to learn about faraway places and people can you actually believe some people say otherwise? I think that's pure bull !@. Computer's today help us with everyday tools, such as cars, cellphones and your everday television! Computer's also make work easier, and you interact with people! I for one think computers benefit society today, and those people who think otherwise should look into it one move step. Cellphones, cars, telephones want! There all made by mankind, but with a bit of technology. Did you know that @PERCENT1 of cars have computers biult in em? By the press of the button, all doors unlocked, by a swith the windows go down, yes, by computer. Now, how do computer's make life easier you say? Well keep reading to find out! The toothpaste, the baseball bats the pencils you we are all made by, the yoou know what! Machines, but programed with computer chips. Oh i remember when my history teacher told me that it took @NUM1 hours to make a baseball bat by a human from scratch. Now it takes like @NUM2 minutes with the help of comuters. If this isn't enough to tell you that computers benefit us, then what will?! Experts say people who use computers a lot don't get outside often to interact with family, but that's false I say! Cellphones are a everyday tool, we use them to talk with each other of long distant calls pay? Well then chat online on your own personal labtop! I hope now you believe computers do really benefit us. With there everday items we use, how they make work easier, and how it does make us interact. We use them everday, and hopefully they'll be around for the longest.",
    display: "Computers, computers, computers. Who doesn't own them right? ...",
  },
];

export default examples;
